# These IDs are pulled from the MBTA API
# They allow us to convert the station IDs into the station names
# They are weirdly hard to find, so I did a little scraping to get them
# I'm sure there is a better way to do this, but it works for now
# Additionally, there may be new / different station IDs in the future

def red_line_map():
    return {'70105': 'Braintree',
            '20761': 'Harvard',
            '5104': 'Davis',
            '70078': 'Downtown Crossing',
            'MM-0023-S': 'JFK/UMass',
            '70087': 'Savin Hill',
            '70198': 'Park Street',
            '32002': 'Quincy Center',
            '70100': 'Wollaston',
            '74617': 'South Station',
            '13': 'Andrew',
            '70065': 'Porter',
            '70093': 'Ashmont',
            '70200': 'Park Street',
            '334': 'Ashmont',
            'Braintree-02': 'Braintree',
            '70101': 'Quincy Center',
            '70077': 'Downtown Crossing',
            'MM-0109': 'Braintree',
            '70097': 'North Quincy',
            '3125': 'North Quincy',
            '70071': 'Kendall/MIT',
            '32003': 'Quincy Center',
            '70102': 'Quincy Center',
            '41031': 'Quincy Adams',
            '70061': 'Alewife',
            '70067': 'Harvard',
            '323': 'Fields Corner',
            '70103': 'Quincy Adams',
            '70066': 'Porter',
            '70082': 'Broadway',
            '70099': 'Wollaston',
            '70094': 'Ashmont',
            '70083': 'Andrew',
            '70076': 'Park Street',
            '70096': 'JFK/UMass',
            '70021': 'Downtown Crossing',
            '70197': 'Park Street',
            'Alewife-01': 'Alewife',
            '70199': 'Park Street',
            '70104': 'Quincy Adams',
            '32005': 'Quincy Center',
            '70261': 'Ashmont',
            '70020': 'Downtown Crossing',
            '141': 'Alewife',
            '70073': 'Charles/MGH',
            '70079': 'South Station',
            '70095': 'JFK/UMass',
            '70084': 'Andrew',
            '70081': 'Broadway',
            '70085': 'JFK/UMass',
            '70092': 'Shawmut',
            '70098': 'North Quincy',
            '70075': 'Park Street',
            '70070': 'Central',
            'FR-0034-01': 'Porter',
            'Braintree-01': 'Braintree',
            'MM-0109-S': 'Braintree',
            'MM-0109-CS': 'Braintree',
            '70074': 'Charles/MGH',
            '70196': 'Park Street',
            '70080': 'South Station',
            '70072': 'Kendall/MIT',
            '74611': 'South Station',
            '70091': 'Shawmut',
            '70086': 'JFK/UMass',
            '70063': 'Davis',
            'FR-0034-02': 'Porter',
            '2076': 'Harvard',
            '70069': 'Central',
            '70088': 'Savin Hill',
            '70090': 'Fields Corner',
            '70068': 'Harvard',
            '70064': 'Davis',
            '38671': 'Braintree',
            '71199': 'Park Street',
            'MM-0079-S': 'Quincy Center',
            '121': 'JFK/UMass',
            '32004': 'Quincy Center',
            '9070061': 'Alewife',
            'Alewife-02': 'Alewife',
            'FR-0034': 'Porter',
            '32001': 'Quincy Center',
            '70089': 'Fields Corner'}

def blue_line_map():
    return {'place-bomnl': 'Bowdoin',
            '70038': 'Bowdoin',
            '70838': 'Bowdoin',
            'place-gover': 'Government Center',
            '70202': 'Government Center',
            'Government Center-Brattle': 'Government Center',
            '70039': 'Government Center',
            '70201': 'Government Center',
            '70040': 'Government Center',
            'place-state': 'State',
            '70022': 'State',
            '70023': 'State',
            '70042': 'State',
            '70041': 'State',
            'place-aqucl': 'Aquarium',
            '70043': 'Aquarium',
            '70044': 'Aquarium',
            'place-mvbcl': 'Maverick',
            '57400': 'Maverick',
            '5740': 'Maverick',
            '70046': 'Maverick',
            '70045': 'Maverick',
            'place-aport': 'Airport',
            '9070047': 'Airport',
            '9170047': 'Airport',
            '7096': 'Airport',
            '7097': 'Airport',
            '70048': 'Airport',
            '70047': 'Airport',
            'place-wimnl': 'Wood Island',
            '70050': 'Wood Island',
            '70049': 'Wood Island',
            '5666': 'Wood Island',
            'place-orhte': 'Orient Heights',
            '70051': 'Orient Heights',
            '70052': 'Orient Heights',
            '5879': 'Orient Heights',
            '15880': 'Orient Heights',
            '5880': 'Orient Heights',
            'place-sdmnl': 'Suffolk Downs',
            '70054': 'Suffolk Downs',
            '70053': 'Suffolk Downs',
            'place-bmmnl': 'Beachmont',
            '70056': 'Beachmont',
            '70055': 'Beachmont',
            'place-rbmnl': 'Revere Beach',
            '70057': 'Revere Beach',
            '70058': 'Revere Beach',
            'place-wondl': 'Wonderland',
            '70060': 'Wonderland',
            '70059': 'Wonderland',
            '15795': 'Wonderland'}

def orange_line_map():
    return {'place-forhl': 'Forest Hills',
            'NEC-2237': 'Forest Hills',
            'NEC-2237-05': 'Forest Hills',
            '10642': 'Forest Hills',
            '875': 'Forest Hills',
            'NEC-2237-03': 'Forest Hills',
            'Forest Hills-01': 'Forest Hills',
            'Forest Hills-02': 'Forest Hills',
            '70001': 'Forest Hills',
            'place-grnst': 'Green Street',
            '70002': 'Green Street',
            '70003': 'Green Street',
            'place-sbmnl': 'Stony Brook',
            '70005': 'Stony Brook',
            '70004': 'Stony Brook',
            'place-jaksn': 'Jackson Square',
            '70006': 'Jackson Square',
            '70007': 'Jackson Square',
            '11531': 'Jackson Square',
            'place-rcmnl': 'Roxbury Crossing',
            '70008': 'Roxbury Crossing',
            '70009': 'Roxbury Crossing',
            'place-rugg': 'Ruggles',
            'NEC-2265-01': 'Ruggles',
            '70010': 'Ruggles',
            '17861': 'Ruggles',
            'NEC-2265': 'Ruggles',
            '17863': 'Ruggles',
            'NEC-2265-03': 'Ruggles',
            '70011': 'Ruggles',
            'NEC-2265-02': 'Ruggles',
            '17862': 'Ruggles',
            'place-masta': 'Massachusetts Avenue',
            '70013': 'Massachusetts Avenue',
            '70012': 'Massachusetts Avenue',
            'place-bbsta': 'Back Bay',
            'NEC-2276': 'Back Bay',
            'WML-0012-05': 'Back Bay',
            'WML-0012-07': 'Back Bay',
            'NEC-2276-01': 'Back Bay',
            '23391': 'Back Bay',
            '70015': 'Back Bay',
            'NEC-2276-02': 'Back Bay',
            'NEC-2276-03': 'Back Bay',
            '70014': 'Back Bay',
            'NEC-2276-B': 'Back Bay',
            'place-tumnl': 'Tufts Medical Center',
            '70016': 'Tufts Medical Center',
            '70017': 'Tufts Medical Center',
            'place-chncl': 'Chinatown',
            '70018': 'Chinatown',
            '70019': 'Chinatown',
            'place-dwnxg': 'Downtown Crossing',
            '70078': 'Downtown Crossing',
            '70077': 'Downtown Crossing',
            '70021': 'Downtown Crossing',
            '70020': 'Downtown Crossing',
            'place-state': 'State',
            '70022': 'State',
            '70023': 'State',
            '70042': 'State',
            '70041': 'State',
            'place-haecl': 'Haymarket',
            '70204': 'Haymarket',
            '70024': 'Haymarket',
            '70203': 'Haymarket',
            '70025': 'Haymarket',
            'place-north': 'North Station',
            'BNT-0000-05': 'North Station',
            'BNT-0000-04': 'North Station',
            'BNT-0000-02': 'North Station',
            'BNT-0000-06': 'North Station',
            'BNT-0000': 'North Station',
            'BNT-0000-01': 'North Station',
            '70206': 'North Station',
            'BNT-0000-10': 'North Station',
            'BNT-0000-B2': 'North Station - Nashua St @ Red Auerbach Way',
            'BNT-0000-08': 'North Station',
            'BNT-0000-03': 'North Station',
            'BNT-0000-07': 'North Station',
            'BNT-0000-B1': 'North Station - Causeway St opp Beverly St',
            '70026': 'North Station',
            '70027': 'North Station',
            '70205': 'North Station',
            'BNT-0000-09': 'North Station',
            'place-ccmnl': 'Community College',
            '70028': 'Community College',
            '70029': 'Community College',
            'place-sull': 'Sullivan Square',
            '29014': 'Sullivan Square',
            '29003': 'Sullivan Square',
            '29006': 'Sullivan Square',
            '29004': 'Sullivan Square',
            '29005': 'Sullivan Square',
            '29007': 'Sullivan Square',
            '29001': 'Sullivan Square',
            '29009': 'Sullivan Square',
            '70030': 'Sullivan Square',
            '29012': 'Sullivan Square',
            '29010': 'Sullivan Square',
            '70031': 'Sullivan Square',
            '29013': 'Sullivan Square',
            '29008': 'Sullivan Square',
            '29002': 'Sullivan Square',
            '29011': 'Sullivan Square',
            'place-astao': 'Assembly',
            '70278': 'Assembly',
            '70279': 'Assembly',
            'place-welln': 'Wellington',
            '70032': 'Wellington',
            '70033': 'Wellington',
            '5271': 'Wellington Station Busway',
            'place-mlmnl': 'Malden Center',
            '5072': 'Malden Center',
            '53270': 'Malden Center',
            '70035': 'Malden Center',
            'WR-0045-S': 'Malden Center',
            '70034': 'Malden Center',
            '5327': 'Malden Center',
            'place-ogmnl': 'Oak Grove',
            'WR-0053-S': 'Oak Grove',
            'Oak Grove-01': 'Oak Grove',
            'Oak Grove-02': 'Oak Grove',
            '9328': 'Oak Grove Busway',
            '70036': 'Oak Grove'}

def green_b_line_map():
    return {'place-gover': 'Government Center',
            '70202': 'Government Center',
            'Government Center-Brattle': 'Government Center',
            '70039': 'Government Center',
            '70201': 'Government Center',
            '70040': 'Government Center',
            'place-pktrm': 'Park Street',
            '70198': 'Park Street',
            '70200': 'Park Street',
            '70076': 'Park Street',
            '70197': 'Park Street',
            '70199': 'Park Street',
            '70075': 'Park Street',
            '70196': 'Park Street',
            '71199': 'Park Street',
            'place-boyls': 'Boylston',
            '70159': 'Boylston',
            '70158': 'Boylston',
            'place-armnl': 'Arlington',
            '70156': 'Arlington',
            '70157': 'Arlington',
            'place-coecl': 'Copley',
            '70155': 'Copley',
            '70154': 'Copley',
            'place-hymnl': 'Hynes Convention Center',
            '70153': 'Hynes Convention Center',
            '70152': 'Hynes Convention Center',
            'place-kencl': 'Kenmore',
            '70151': 'Kenmore',
            '71150': 'Kenmore',
            '70150': 'Kenmore',
            '899': 'Kenmore',
            '71151': 'Kenmore',
            'place-bland': 'Blandford Street',
            '70148': 'Blandford Street',
            '70149': 'Blandford Street',
            'place-buest': 'Boston University East',
            '70147': 'Boston University East',
            '70146': 'Boston University East',
            'place-bucen': 'Boston University Central',
            '70145': 'Boston University Central',
            '70144': 'Boston University Central',
            'place-amory': 'Amory Street',
            '170140': 'Amory Street',
            '170141': 'Amory Street',
            'place-babck': 'Babcock Street',
            '170137': 'Babcock Street',
            '170136': 'Babcock Street',
            'place-brico': "Packard's Corner",
            '70135': "Packard's Corner",
            '70134': "Packard's Corner",
            'place-harvd': 'Harvard Avenue',
            '70130': 'Harvard Avenue',
            '70131': 'Harvard Avenue',
            'place-grigg': 'Griggs Street',
            '70129': 'Griggs Street',
            '70128': 'Griggs Street',
            'place-alsgr': 'Allston Street',
            '70127': 'Allston Street',
            '70126': 'Allston Street',
            'place-wrnst': 'Warren Street',
            '70124': 'Warren Street',
            '70125': 'Warren Street',
            'place-wascm': 'Washington Street',
            '70120': 'Washington Street',
            '70121': 'Washington Street',
            'place-sthld': 'Sutherland Road',
            '70117': 'Sutherland Road',
            '70116': 'Sutherland Road',
            'place-chswk': 'Chiswick Road',
            '70114': 'Chiswick Road',
            '70115': 'Chiswick Road',
            'place-chill': 'Chestnut Hill Avenue',
            '70113': 'Chestnut Hill Avenue',
            '70112': 'Chestnut Hill Avenue',
            'place-sougr': 'South Street',
            '70110': 'South Street',
            '70111': 'South Street',
            'place-lake': 'Boston College',
            '70106': 'Boston College',
            '70107': 'Boston College'}

def green_c_line_map():
    return {'place-clmnl': 'Cleveland Circle',
            '70238': 'Cleveland Circle',
            '70237': 'Cleveland Circle',
            'place-engav': 'Englewood Avenue',
            '70236': 'Englewood Avenue',
            '70235': 'Englewood Avenue',
            'place-denrd': 'Dean Road',
            '70234': 'Dean Road',
            '70233': 'Dean Road',
            'place-tapst': 'Tappan Street',
            '70232': 'Tappan Street',
            '70231': 'Tappan Street',
            'place-bcnwa': 'Washington Square',
            '70229': 'Washington Square',
            '70230': 'Washington Square',
            'place-fbkst': 'Fairbanks Street',
            '70228': 'Fairbanks Street',
            '70227': 'Fairbanks Street',
            'place-bndhl': 'Brandon Hall',
            '70226': 'Brandon Hall',
            '70225': 'Brandon Hall',
            'place-sumav': 'Summit Avenue',
            '70224': 'Summit Avenue',
            '70223': 'Summit Avenue',
            'place-cool': 'Coolidge Corner',
            '70219': 'Coolidge Corner',
            '70220': 'Coolidge Corner',
            'place-stpul': 'Saint Paul Street',
            '70217': 'Saint Paul Street',
            '70218': 'Saint Paul Street',
            'place-kntst': 'Kent Street',
            '70216': 'Kent Street',
            '70215': 'Kent Street',
            'place-hwsst': 'Hawes Street',
            '70213': 'Hawes Street',
            '70214': 'Hawes Street',
            'place-smary': "Saint Mary's Street",
            '70211': "Saint Mary's Street",
            '70212': "Saint Mary's Street",
            'place-kencl': 'Kenmore',
            '70151': 'Kenmore',
            '71150': 'Kenmore',
            '70150': 'Kenmore',
            '899': 'Kenmore',
            '71151': 'Kenmore',
            'place-hymnl': 'Hynes Convention Center',
            '70153': 'Hynes Convention Center',
            '70152': 'Hynes Convention Center',
            'place-coecl': 'Copley',
            '70155': 'Copley',
            '70154': 'Copley',
            'place-armnl': 'Arlington',
            '70156': 'Arlington',
            '70157': 'Arlington',
            'place-boyls': 'Boylston',
            '70159': 'Boylston',
            '70158': 'Boylston',
            'place-pktrm': 'Park Street',
            '70198': 'Park Street',
            '70200': 'Park Street',
            '70076': 'Park Street',
            '70197': 'Park Street',
            '70199': 'Park Street',
            '70075': 'Park Street',
            '70196': 'Park Street',
            '71199': 'Park Street',
            'place-gover': 'Government Center',
            '70202': 'Government Center',
            'Government Center-Brattle': 'Government Center',
            '70039': 'Government Center',
            '70201': 'Government Center',
            '70040': 'Government Center'}

def green_d_line_map():
    return {'place-river': 'Riverside',
            '70161': 'Riverside',
            '70160': 'Riverside',
            '38155': 'Riverside',
            'place-woodl': 'Woodland',
            '70163': 'Woodland',
            '70162': 'Woodland',
            'place-waban': 'Waban',
            '70164': 'Waban',
            '70165': 'Waban',
            'place-eliot': 'Eliot',
            '70167': 'Eliot',
            '70166': 'Eliot',
            'place-newtn': 'Newton Highlands',
            '70168': 'Newton Highlands',
            '8203': 'Newton Highlands',
            '70169': 'Newton Highlands',
            '8155': 'Newton Highlands',
            'place-newto': 'Newton Centre',
            '70171': 'Newton Centre',
            '70170': 'Newton Centre',
            'place-chhil': 'Chestnut Hill',
            '70172': 'Chestnut Hill',
            '70173': 'Chestnut Hill',
            'place-rsmnl': 'Reservoir',
            '70175': 'Reservoir',
            '70174': 'Reservoir',
            '21917': 'Reservoir',
            'place-bcnfd': 'Beaconsfield',
            '70177': 'Beaconsfield',
            '70176': 'Beaconsfield',
            'place-brkhl': 'Brookline Hills',
            '70178': 'Brookline Hills',
            '70179': 'Brookline Hills',
            'place-bvmnl': 'Brookline Village',
            '70180': 'Brookline Village',
            '70181': 'Brookline Village',
            'place-longw': 'Longwood',
            '70182': 'Longwood',
            '70183': 'Longwood',
            'place-fenwy': 'Fenway',
            '70187': 'Fenway',
            '70186': 'Fenway',
            'place-kencl': 'Kenmore',
            '70151': 'Kenmore',
            '71150': 'Kenmore',
            '70150': 'Kenmore',
            '899': 'Kenmore',
            '71151': 'Kenmore',
            'place-hymnl': 'Hynes Convention Center',
            '70153': 'Hynes Convention Center',
            '70152': 'Hynes Convention Center',
            'place-coecl': 'Copley',
            '70155': 'Copley',
            '70154': 'Copley',
            'place-armnl': 'Arlington',
            '70156': 'Arlington',
            '70157': 'Arlington',
            'place-boyls': 'Boylston',
            '70159': 'Boylston',
            '70158': 'Boylston',
            'place-pktrm': 'Park Street',
            '70198': 'Park Street',
            '70200': 'Park Street',
            '70076': 'Park Street',
            '70197': 'Park Street',
            '70199': 'Park Street',
            '70075': 'Park Street',
            '70196': 'Park Street',
            '71199': 'Park Street',
            'place-gover': 'Government Center',
            '70202': 'Government Center',
            'Government Center-Brattle': 'Government Center',
            '70039': 'Government Center',
            '70201': 'Government Center',
            '70040': 'Government Center',
            'place-haecl': 'Haymarket',
            '70204': 'Haymarket',
            '70024': 'Haymarket',
            '70203': 'Haymarket',
            '70025': 'Haymarket',
            'place-north': 'North Station',
            'BNT-0000-05': 'North Station',
            'BNT-0000-04': 'North Station',
            'BNT-0000-02': 'North Station',
            'BNT-0000-06': 'North Station',
            'BNT-0000': 'North Station',
            'BNT-0000-01': 'North Station',
            '70206': 'North Station',
            'BNT-0000-10': 'North Station',
            'BNT-0000-B2': 'North Station - Nashua St @ Red Auerbach Way',
            'BNT-0000-08': 'North Station',
            'BNT-0000-03': 'North Station',
            'BNT-0000-07': 'North Station',
            'BNT-0000-B1': 'North Station - Causeway St opp Beverly St',
            '70026': 'North Station',
            '70027': 'North Station',
            '70205': 'North Station',
            'BNT-0000-09': 'North Station',
            'place-spmnl': 'Science Park/West End',
            '70207': 'Science Park/West End',
            '70208': 'Science Park/West End',
            'place-lech': 'Lechmere',
            '70500': 'Lechmere',
            '70502': 'Lechmere',
            '70501': 'Lechmere',
            'place-unsqu': 'Union Square',
            'Union Square-01': 'Union Square',
            '70503': 'Union Square',
            'Union Square-02': 'Union Square',
            '70504': 'Union Square'}

def green_e_line_map():
    return {'place-hsmnl': 'Heath Street',
            '70260': 'Heath Street',
            'place-bckhl': 'Back of the Hill',
            '70257': 'Back of the Hill',
            '70258': 'Back of the Hill',
            'place-rvrwy': 'Riverway',
            '70255': 'Riverway',
            '70256': 'Riverway',
            'place-mispk': 'Mission Park',
            '70253': 'Mission Park',
            '70254': 'Mission Park',
            'place-fenwd': 'Fenwood Road',
            '70252': 'Fenwood Road',
            '70251': 'Fenwood Road',
            'place-brmnl': 'Brigham Circle',
            '70249': 'Brigham Circle',
            '70250': 'Brigham Circle',
            'place-lngmd': 'Longwood Medical Area',
            '70247': 'Longwood Medical Area',
            '70248': 'Longwood Medical Area',
            'place-mfa': 'Museum of Fine Arts',
            '70246': 'Museum of Fine Arts',
            '70245': 'Museum of Fine Arts',
            'place-nuniv': 'Northeastern University',
            '70244': 'Northeastern University',
            '70243': 'Northeastern University',
            'place-symcl': 'Symphony',
            '70241': 'Symphony',
            '70242': 'Symphony',
            'place-prmnl': 'Prudential',
            '70240': 'Prudential',
            '70239': 'Prudential',
            'place-coecl': 'Copley',
            '70155': 'Copley',
            '70154': 'Copley',
            'place-armnl': 'Arlington',
            '70156': 'Arlington',
            '70157': 'Arlington',
            'place-boyls': 'Boylston',
            '70159': 'Boylston',
            '70158': 'Boylston',
            'place-pktrm': 'Park Street',
            '70198': 'Park Street',
            '70200': 'Park Street',
            '70076': 'Park Street',
            '70197': 'Park Street',
            '70199': 'Park Street',
            '70075': 'Park Street',
            '70196': 'Park Street',
            '71199': 'Park Street',
            'place-gover': 'Government Center',
            '70202': 'Government Center',
            'Government Center-Brattle': 'Government Center',
            '70039': 'Government Center',
            '70201': 'Government Center',
            '70040': 'Government Center',
            'place-haecl': 'Haymarket',
            '70204': 'Haymarket',
            '70024': 'Haymarket',
            '70203': 'Haymarket',
            '70025': 'Haymarket',
            'place-north': 'North Station',
            'BNT-0000-05': 'North Station',
            'BNT-0000-04': 'North Station',
            'BNT-0000-02': 'North Station',
            'BNT-0000-06': 'North Station',
            'BNT-0000': 'North Station',
            'BNT-0000-01': 'North Station',
            '70206': 'North Station',
            'BNT-0000-10': 'North Station',
            'BNT-0000-B2': 'North Station - Nashua St @ Red Auerbach Way',
            'BNT-0000-08': 'North Station',
            'BNT-0000-03': 'North Station',
            'BNT-0000-07': 'North Station',
            'BNT-0000-B1': 'North Station - Causeway St opp Beverly St',
            '70026': 'North Station',
            '70027': 'North Station',
            '70205': 'North Station',
            'BNT-0000-09': 'North Station',
            'place-spmnl': 'Science Park/West End',
            '70207': 'Science Park/West End',
            '70208': 'Science Park/West End',
            'place-lech': 'Lechmere',
            '70500': 'Lechmere',
            '70502': 'Lechmere',
            '70501': 'Lechmere',
            'place-esomr': 'East Somerville',
            '70514': 'East Somerville',
            '70513': 'East Somerville',
            'place-gilmn': 'Gilman Square',
            '70506': 'Gilman Square',
            '70505': 'Gilman Square',
            'place-mgngl': 'Magoun Square',
            '70508': 'Magoun Square',
            '70507': 'Magoun Square',
            'place-balsq': 'Ball Square',
            '70510': 'Ball Square',
            '70509': 'Ball Square',
            'place-mdftf': 'Medford/Tufts',
            '70512': 'Medford/Tufts',
            '70511': 'Medford/Tufts'}
# Dictionary mapping line names to their respective map functions
station_id_maps = {
    "Red": red_line_map,
    "Blue": blue_line_map,
    "Orange": orange_line_map,
    "Green-B": green_b_line_map,
    "Green-C": green_c_line_map,
    "Green-D": green_d_line_map,
    "Green-E": green_e_line_map
}
